### ISSUE TITLE
Should close filter overlay on clickout

### ISSUE THREAD

**Issue by chrisjanusa** [chrisjanusa/RandomRestaurantKotlin#18]
When the user clicks on the shadowed overlay, it should perform a cancel.

**Comment by chrisjanusa** [comment]
After making the background clickable, should be able to add onClickListener inside ShadeFragment.kt found in the filter_base package

**Comment by chrisjanusa** [comment]
@joelewing do you think it should cancel (disregarding any changes they made), apply the current selected value, or save their selected but not apply it so if they reopen the filter it is still selected but not applied

**Comment by chrisjanusa** [comment]
I am leaning towards cancel but want to see if you agree

**Comment by chrisjanusa** [comment]
I am going to merge it in with cancel for the time being. @joelewing let me know if you think we should change it.

**Comment by joelewing** [comment]
Yes, I think it should be the same as cancel as long as the apply option is visible enough. I could maybe do some usability testing at some point to see if it makes sense to other people. But for now, I agree!

**Comment by chrisjanusa** [comment]
Awesome! I will close this issue then
