### ISSUE TITLE
Make apply button more visible

### ISSUE THREAD

**Issue by chrisjanusa** [chrisjanusa/RandomRestaurantKotlin#25]

**Comment by chrisjanusa** [comment]
![Screenshot_20200208-181850_Random Restaurant Picker](https://user-images.githubusercontent.com/19912368/74095178-e3c8d000-4aa1-11ea-9481-60f0cf552d7b.jpg)
![Screenshot_20200208-182717_Random Restaurant Picker](https://user-images.githubusercontent.com/19912368/74095179-e5929380-4aa1-11ea-92a1-84179a1ef813.jpg)
![Screenshot_20200208-183232_Random Restaurant Picker](https://user-images.githubusercontent.com/19912368/74095180-e6c3c080-4aa1-11ea-85e9-b801dc6aecb1.jpg)
![Screenshot_20200208-183349_Random Restaurant Picker](https://user-images.githubusercontent.com/19912368/74095181-e88d8400-4aa1-11ea-8fe3-fcdcc3acf7cc.jpg)
![Screenshot_20200208-183434_Random Restaurant Picker](https://user-images.githubusercontent.com/19912368/74095184-ea574780-4aa1-11ea-9204-3351f14564f2.jpg)
![Screenshot_20200208-183507_Random Restaurant Picker](https://user-images.githubusercontent.com/19912368/74095188-ecb9a180-4aa1-11ea-9b3d-d9fd6b3803b0.jpg)

**Comment by chrisjanusa** [comment]
@joelewing any thoughts on these options for the buttons within the filter overlays???

**Comment by joelewing** [comment]
![74095184-ea574780-4aa1-11ea-9204-3351f14564f2](https://user-images.githubusercontent.com/9755486/74095344-f4cf0c80-4ab4-11ea-8064-96f6fe71559c.jpg)

This one looks the best because it emphasized the apply action, and not the other ones.

I would recommend using a different color for "primary button actions" and the color used to indicate that something is selected.

Better yet, have checkboxes for the dietary options instead of making them look like buttons. Just my two cents.

With this few options, I'd remove the "Reset" button.

**Comment by chrisjanusa** [comment]
![Screenshot_20200208-194208_Random Restaurant Picker](https://user-images.githubusercontent.com/19912368/74095835-335fc980-4aab-11ea-92e5-e1fec7420d6c.jpg)

**Comment by chrisjanusa** [comment]
The reason Reset is present is that I reuse the UI for all the filter overlays so the only thing that changes is the title and the inside part. I definitely see a use case for reset in all the other filters so I think keep it for consistency

**Comment by chrisjanusa** [comment]
I agree with the same color issue. Not sure this is the place for a checkbox. I will play with it and see what I like.

**Comment by chrisjanusa** [comment]
![Screenshot_20200208-194851_Random Restaurant Picker](https://user-images.githubusercontent.com/19912368/74095919-88e8a600-4aac-11ea-8541-67d3c421b5fc.jpg)

**Comment by chrisjanusa** [comment]
Yea this does not look great. The app currently has white, black and the two shades of red that are used though.

**Comment by chrisjanusa** [comment]
![Screenshot_20200209-162056_Random Restaurant Picker](https://user-images.githubusercontent.com/19912368/74113320-54cabf00-4b58-11ea-8062-488c7a6cc078.jpg)
![Screenshot_20200209-162110_Random Restaurant Picker](https://user-images.githubusercontent.com/19912368/74113324-56948280-4b58-11ea-9af6-86c9bc7aee9f.jpg)

**Comment by chrisjanusa** [comment]
@joelewing thoughts?
